### PR TITLE
:pencil: docs(readme): Fix typo

### PR DESCRIPTION
**Pull request by anselal**
Just a minor typo fix. You misspelled Sublime 3 times.

### CODE REVIEW

**Comment by anselal** [comment]
You misspelled 'open' too...

**Comment by vanleo2001** [comment]
Readme Fix, thanks you @SoulisTech.

**Comment by anselal** [comment]
The whole reason for pull requests is that you merge them and not do the fix by yourself but ok.

**Comment by anselal** [comment]
Another typo found. Misspelled unpack (unapck)

**Comment by vanleo2001** [comment]
Fix it. Thanks again.

**Pull request closed without merging**
